apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: services.miloapis.com-monitoredresourcetype
spec:
  serviceRef:
    name: "services.miloapis.com"
  kind: MonitoredResourceType
  plural: monitoredresourcetypes
  singular: monitoredresourcetype
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
    - updateStatus
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Organization
