apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: services
    app.kubernetes.io/managed-by: kustomize
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: services
    app.kubernetes.io/managed-by: kustomize
  name: services-serving-cert
spec:
  # The Service name and namespace get substituted in by kustomize
  # replacements in the consuming overlay.
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: services-webhook-cert
