---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-controller-manager
rules:
- apiGroups:
  - billing.miloapis.com
  resources:
  - meterdefinitions
  - monitoredresourcetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.datumapis.com
  resources:
  - locationbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.datumapis.com
  resources:
  - locations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quota.miloapis.com
  resources:
  - claimcreationpolicies
  - resourcegrants
  - resourceregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - organizations
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - services.miloapis.com
  resources:
  - serviceavailabilities
  - serviceconfigurations
  - serviceconsumers
  - serviceentitlements
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.miloapis.com
  resources:
  - serviceavailabilities/finalizers
  - serviceconfigurations/finalizers
  - serviceentitlements/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - services.miloapis.com
  resources:
  - serviceavailabilities/status
  - serviceconfigurations/status
  - serviceconsumers/status
  - serviceentitlements/status
  - services/status
  verbs:
  - get
  - patch
  - update
