## Append samples of your project ##
resources:
- services_v1alpha1_service.yaml
- services_v1alpha1_meterdefinition.yaml
- services_v1alpha1_monitoredresourcetype.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
