apiVersion: apiserver.config.miloapis.com/v1alpha1
kind: ServicesOperator
metricsServer:
  bindAddress: "0"

webhookServer:
  tls:
    secretRef:
      name: services-webhook-cert
      namespace: kube-system
