//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ServicesOperator{}, func(obj interface{}) { SetObjectDefaults_ServicesOperator(obj.(*ServicesOperator)) })
	return nil
}

func SetObjectDefaults_ServicesOperator(in *ServicesOperator) {
	SetDefaults_ServicesOperator(in)
	SetDefaults_MetricsServerConfig(&in.MetricsServer)
	SetDefaults_TLSConfig(&in.MetricsServer.TLS)
	if in.WebhookServer != nil {
		SetDefaults_WebhookServerConfig(in.WebhookServer)
		SetDefaults_TLSConfig(&in.WebhookServer.TLS)
	}
}
