name: Validate Kustomize

on:
  push:

jobs:
  validate-kustomize:
    permissions:
      contents: read
    uses: datum-cloud/actions/.github/workflows/validate-kustomize.yaml@v1.12.1
    secrets: inherit
